steps:
  # pull cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull $_GCR_IMAGE_PATH:$TAG_NAME:latest || exit 0' ]
    id: 'pull-server'
    waitFor: [ '-' ]

  # build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '$_GCR_IMAGE_PATH:$TAG_NAME',
            '--cache-from', '$_GCR_IMAGE_PATH:$TAG_NAME:latest',
            '--file', './server/Dockerfile', '.' ]
    id: 'build-server'
    waitFor:
      - 'pull-server'

  # save
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_GCR_IMAGE_PATH:$TAG_NAME' ]
    id: 'save-server'
    waitFor:
      - 'build-server'

images:
  - $_GCR_IMAGE_PATH:$TAG_NAME

timeout: 1200s
