steps:
  # pull cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull $_GCR_IMAGE_PATH || exit 0' ]
    id: 'pull-server'
    waitFor: [ '-' ]

  # build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '$_GCR_IMAGE_PATH:$TAG_NAME',
            '-t', '$_GCR_IMAGE_PATH',
            '--cache-from', '$_GCR_IMAGE_PATH',
            '--file', './server/Dockerfile', '.' ]
    id: 'build-server'
    waitFor:
      - 'pull-server'

  # save
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_GCR_IMAGE_PATH:$TAG_NAME' ]
    id: 'save-server-tag'
    waitFor:
      - 'build-server'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '$_GCR_IMAGE_PATH' ]
    id: 'save-server-latest'
    waitFor:
      - 'build-server'

images:
  - $_GCR_IMAGE_PATH:$TAG_NAME
  - $_GCR_IMAGE_PATH

timeout: 1200s
