version: "3.8"

services:
  local:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        - VERSION="local development"
    restart: unless-stopped
    command:
      - "npm"
      - "run"
      - "production"
    ports:
      - "8080:8080"
    environment:
      PORT: 8080

  remote:
    image: gcr.io/frame-one-software-placeholder/image:latest
    ports:
      - "8081:8081"
    environment:
      PORT: 8081