version: "3.8"

services:
  local:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REDIRECT_TO: "https://google.ca"

  remote:
    image: gcr.io/frame-one-software-placeholder/image:latest
    ports:
      - "8081:8081"
    environment:
      PORT: 8081